sflow:
  agent_ip: "10.0.1.100"
  sample_rate: 1000
  version: 5

processing:
  channel_buffer: 30000
  concurrent_sends: true

outputs:
  - type: "clickhouse"
    config:
      dsn: "localhost:9000"
      database: "flows"
      username: "default"
      password: ""
      table: "network_flows"
      batch_size: 3000
      flush_interval: "5s"
      tls: false

log_level: "info"